version: '3.7'
services:
  stream_server:
    build:
      context: .
      dockerfile: Dockerfile-alpine

    # Commented are for Kompose convert
    # image: harikaram/stream_server
    restart: unless-stopped #always


    # env_file:
      # - .env
    command: nginx -g "daemon off;"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./players:/usr/local/nginx/html/players
    ports:
      - "1935:1935"
      - "8080:8080"

# volumes:
#    ./conf/nginx.conf:
# #   db:
# #   bundler_gems:
